FROM node:16
RUN mkdir -p /opt/app
WORKDIR /opt/app
ARG DB_USER
ENV DB_USER $DB_USER
ARG DB_PASSWORD
ENV DB_PASSWORD $DB_PASSWORD
RUN adduser app
COPY ./ .
RUN npm install
RUN chown -R app /opt/app
USER app
EXPOSE 5000
CMD [ "node", "server.js"]